apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjenkins
  namespace: mas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjenkins
  template:
    metadata:
      labels:
        app: mjenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc

