apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: my 
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000  # Adjust the nodePort if needed
  selector:
    app: jenkins

